/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Driver;

import static Driver.driver.me;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.SwingUtilities;

/**
 *
 * @author Vincentius
 */
public class deleteSubProject extends javax.swing.JFrame {

    static final String DB_URL = "jdbc:mysql://localhost/projectmanagementtubes";
    static final String DB_USER = "root";
    static final String DB_PASS = "";
    static Connection conn;
    static Statement stmt;
    static ResultSet rs;
    
    /**
     * Creates new form deleteSubProject
     */
    String nama,induk;
    private class handler implements ActionListener {
        
        private ArrayList<String> toArrayString(String target) {
            ArrayList<String> res = new ArrayList<>();
            for (int i = 0; i < target.length(); i++) {
                String result = "";
                if (target.charAt(i) == '"') {
                    i++;
                    while (target.charAt(i) != '"') {
                        result += target.charAt(i);
                        i++;
                    }
                    res.add(result);
                    result = "";
                    i++;
                }
            }
            return res;
        }
        
        public void actionPerformed(ActionEvent e) {
            try {
                conn = DriverManager.getConnection(DB_URL, DB_USER,DB_PASS);
                stmt = conn.createStatement();
                
                String st = "";
                st = "SELECT id_project FROM project WHERE nama = '" + induk + "'";
                rs = stmt.executeQuery(st);
                int id = 0;
                while (rs.next()) {
                    id = rs.getInt("id_project");
                }
                st = "DELETE FROM subproject WHERE nama = ?";
                PreparedStatement ps = conn.prepareStatement(st);
                ps.setString(1, nama);
                ps.execute();
                
                st = "SELECT subproject FROM project WHERE id_project = " + id;
                rs = stmt.executeQuery(st);
                String sbj = "";
                while (rs.next()) {
                    sbj = rs.getString("subProject");
                }
                ArrayList<String> proj = new ArrayList<>();
                proj = toArrayString(sbj);
                int tmp = proj.indexOf(nama);
                proj.remove(tmp);
                String sp = "[";
                for (String s : proj) {
                    sp += "\"" + s + "\",";
                }
                sp += "]";
                
                st = "UPDATE project SET subProject = ? WHERE id_project = ?";
                ps = conn.prepareStatement(st);
                ps.setString(1, sp);
                ps.setInt(2, id);
                ps.execute();
                
                stmt.close();
                conn.close();
            } catch (Exception a) {
                a.printStackTrace();
            } finally {
                me.loadDB();
                SwingUtilities.updateComponentTreeUI(me);
                dispose();
            }
        }
    }
    
    private class handler2 implements ActionListener {
        public void actionPerformed(ActionEvent e) {
            me.loadDB();
            dispose();
        }
    }
    
    void launch(String nama, String induk) {
        this.nama = nama;
        this.induk = induk;
        cancelButton.addActionListener(new handler2());
        OKButton.addActionListener(new handler());
    }
    
    public deleteSubProject(String nama, String induk) {
        initComponents();
        launch(nama, induk);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        OKButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Are You Sure Want to Delete This SubProject?");

        cancelButton.setText("Cancel");

        OKButton.setText("OK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(OKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(OKButton))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
