/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Driver;

import static Driver.driver.me;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.SwingUtilities;

/**
 *
 * @author Yozha
 */
public class deleteProjectLayer extends javax.swing.JFrame {
    static final String DB_URL = "jdbc:mysql://localhost/projectmanagementtubes";
    static final String DB_USER = "root";
    static final String DB_PASS = "";
    static Connection conn;
    static Statement stmt;
    static ResultSet rs;

    /**
     * Creates new form deleteProjectLayer
    
    */
    String nama;
    
    private ArrayList<String> toArrayString(String target) {
        
        /*
            I.S. terdefinisi sebuah string dari DATABASE (varchar) pada table project.
                 kolom subproject dan worker akan dilakukan perubahan tipe data
                 menjadi array list String untuk dimasukkan dalam element atribut
                 project dan subproject
            F.S. perubahan tipe data dari String menjadi array list String
        */
        
        ArrayList<String> res = new ArrayList<>();
        for (int i = 0; i < target.length(); i++) {
            String result = "";
            if (target.charAt(i) == '"') {
                i++;
                while (target.charAt(i) != '"') {
                    result += target.charAt(i);
                    i++;
                }
                res.add(result);
                result = "";
                i++;
            }
        }
        return res;
    }
    
    private class handler implements ActionListener {
        public void actionPerformed(ActionEvent e) {
            try {
                conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASS);
                stmt = conn.createStatement();
                
                String st = "";
                st = "SELECT subproject FROM project WHERE nama = '" + nama + "'";
                rs = stmt.executeQuery(st);
                String sj  = "";
                while (rs.next()) {
                    sj = rs.getString("subproject");
                }
                
                ArrayList<String> rej = new ArrayList<>();
                rej = toArrayString(sj);
                for (String s : rej){
                    st = "DELETE FROM subproject WHERE nama = ?";
                    PreparedStatement ps = conn.prepareStatement(st);
                    ps.setString(1, s);
                    ps.execute();
                }
                
                st = "SELECT id_project FROM project WHERE nama = '" + nama + "'";
                rs = stmt.executeQuery(st);
                int id = 0;
                while (rs.next()) {
                    id = rs.getInt("id_project");
                }
                
                st = "DELETE FROM customer WHERE id_project = ?";
                PreparedStatement ps = conn.prepareStatement(st);
                ps.setInt(1, id);
                ps.execute();
                
                st = "DELETE FROM project WHERE nama = ?";
                ps = conn.prepareStatement(st);
                ps.setString(1, nama);
                ps.execute();
                
                stmt.close();
                conn.close();
            } catch (Exception a) {
                a.printStackTrace();
            } finally {
                me.loadDB();
                SwingUtilities.updateComponentTreeUI(me);
                dispose();
            }
        }
    }
    
    private class handler2 implements ActionListener {
        public void actionPerformed(ActionEvent e) {
            me.loadDB();
            dispose();
        }
    }
    
    
    void launch(String nama){
        this.nama = nama;
        yesButton.addActionListener(new handler());
        cancelButton.addActionListener(new handler2());
    }
    
    public deleteProjectLayer(String nama) {
        initComponents();
        launch(nama);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelButton = new javax.swing.JButton();
        yesButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cancelButton.setText("Cancel");

        yesButton.setText("Yes");

        jLabel1.setText("Are U Sure Want To Delete This Data?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(yesButton))
                    .addComponent(jLabel1))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(yesButton))
                .addGap(115, 115, 115))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
  
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton yesButton;
    // End of variables declaration//GEN-END:variables
}
